# Generated by Django 4.2.5 on 2023-09-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greet', models.CharField(max_length=20)),
                ('greet2', models.CharField(max_length=100)),
                ('mainPic', models.ImageField(upload_to='pages/assets/img/')),
            ],
        ),
    ]
