# Generated by Django 4.2.5 on 2023-09-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
