# Generated by Django 4.2.5 on 2023-09-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greet', models.CharField(max_length=20)),
                ('mainPic', models.ImageField(upload_to='pages/assets/img/')),
            ],
        ),
        migrations.CreateModel(
            name='MyTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myTitle', models.CharField(max_length=50)),
                ('fkTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.home')),
            ],
        ),
    ]
