# Generated by Django 4.2.5 on 2023-09-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_about_skill_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RemoveField(
            model_name='mytitles',
            name='fkTitle',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='fkSkills',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='MyTitles',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
