# Generated by Django 4.2.5 on 2023-09-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0005_delete_about_remove_mytitles_fktitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutDescSec', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greet', models.CharField(max_length=20)),
                ('mainPic', models.ImageField(upload_to='pages/assets/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portImg', models.ImageField(upload_to='pages/assets/img/')),
                ('description', models.TextField()),
                ('link', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillsCategory', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MyTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myTitle', models.CharField(max_length=50)),
                ('fkTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.home')),
            ],
        ),
        migrations.CreateModel(
            name='My_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillList', models.CharField(max_length=20)),
                ('fkSkills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.skills')),
            ],
        ),
    ]
