# Generated by Django 4.2.5 on 2023-09-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RemoveField(
            model_name='my_skills',
            name='fkSkills',
        ),
        migrations.RemoveField(
            model_name='mytitles',
            name='fkTitle',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='My_skills',
        ),
        migrations.DeleteModel(
            name='MyTitles',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
