# Generated by Django 4.2.5 on 2023-09-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='mytitles',
            name='fkTitle',
        ),
        migrations.RemoveField(
            model_name='portdetails',
            name='fkToPortfolio',
        ),
        migrations.RemoveField(
            model_name='portdetailsimg',
            name='fkPortfolio',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='MyTitles',
        ),
        migrations.DeleteModel(
            name='PortDetails',
        ),
        migrations.DeleteModel(
            name='PortDetailsImg',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
