# Generated by Django 4.2.5 on 2023-09-26 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0009_delete_about_delete_contact_remove_mytitles_fktitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutDescSec', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlMyCV', models.FileField(upload_to='static/cv')),
                ('contactEmail', models.CharField(max_length=50)),
                ('contactPhone', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greet', models.CharField(max_length=20)),
                ('coverPic', models.ImageField(upload_to='static/img/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portLabel', models.CharField(max_length=50)),
                ('portLabelDesc', models.TextField()),
                ('portCoverImg', models.ImageField(upload_to='static/img/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='static/img')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillsName', models.CharField(max_length=20)),
                ('skillsImg', models.ImageField(upload_to='static/img/')),
            ],
        ),
        migrations.CreateModel(
            name='PortDetailsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portImg', models.ImageField(upload_to='static/img/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fkPortfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTitle', models.CharField(max_length=50)),
                ('projectUrl', models.URLField(blank=True)),
                ('mainDesc', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fkToPortfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='MyTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myJobs', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fkTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.home')),
            ],
        ),
    ]
