# Generated by Django 4.2.5 on 2023-09-26 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skillsURL',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
