# Generated by Django 4.2.5 on 2023-09-26 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_skills_skillsurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='dlMyCV',
            new_name='CV',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contactEmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contactPhone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
