# Generated by Django 4.2.5 on 2023-09-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_rename_dlmycv_contact_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
