# Generated by Django 4.2.5 on 2023-09-27 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_portfolio_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portURL',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
